-- 1. 將該欄位轉換為 Identity，並自動繼承目前數值
-- ALTER TABLE inv_stocks 
-- ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;


-- 2. 關鍵：設定序列的起始值，確保下次編號從最大的 ID + 1 開始
SELECT setval(
    pg_get_serial_sequence('inv_stocks', 'id'), 
    (SELECT MAX(id) FROM inv_stocks)
);