
-- 向上溯源：找出一塊餘料的「祖宗十八代」
WITH RECURSIVE material_lineage AS (
    -- 1. Anchor 部份：先找出起始的那一塊料
    SELECT id, serial_number, parent_id, length, 0 AS level
    FROM workpiece_inventory
    WHERE id = 5  -- 這裡輸入你想查詢的餘料 ID

    UNION ALL

    -- 2. Recursive 部份：根據 parent_id 往上串連
    SELECT t.id, t.serial_number, t.parent_id, t.length, ml.level + 1
    FROM workpiece_inventory t
    INNER JOIN material_lineage ml ON t.id = ml.parent_id
)
SELECT * FROM material_lineage ORDER BY level DESC;

-- 向下展開：看這根母材「生了多少餘料」
WITH RECURSIVE family_tree AS (
    -- 1. Anchor 部份：從最頂層的母材開始
    SELECT id, serial_number, parent_id, length, status
    FROM workpiece_inventory
    WHERE id = 1

    UNION ALL

    -- 2. Recursive 部份：找所有子孫
    SELECT t.id, t.serial_number, t.parent_id, t.length, t.status
    FROM workpiece_inventory t
    INNER JOIN family_tree ft ON t.parent_id = ft.id
)
SELECT * FROM family_tree;



-- 1. 庫存表 (使用 IDENTITY 代替 SERIAL，這是符合 SQL 標準的現代寫法)
CREATE TABLE workpiece_inventory (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    serial_number VARCHAR(100) UNIQUE,
    outer_diameter DECIMAL(10, 2) NOT NULL,
    length DECIMAL(10, 2) NOT NULL,
    
    -- 自關聯：指向母材的整數 ID
    parent_id INTEGER REFERENCES workpiece_inventory(id) ON DELETE SET NULL,
    
    status VARCHAR(20) DEFAULT 'available', -- available, consumed, scrap
    note TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 2. 需求表
CREATE TABLE cutting_requirements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    outer_diameter DECIMAL(10, 2) NOT NULL,
    length DECIMAL(10, 2) NOT NULL,
    quantity INTEGER DEFAULT 1,
    priority INTEGER DEFAULT 1,
    order_status VARCHAR(20) DEFAULT 'pending', -- pending, completed
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. 切割日誌
CREATE TABLE cutting_logs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_inventory_id INTEGER REFERENCES workpiece_inventory(id),
    requirement_id INTEGER REFERENCES cutting_requirements(id),
    cut_length DECIMAL(10, 2) NOT NULL,
    remaining_length DECIMAL(10, 2) NOT NULL,
    executed_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 4. 索引優化 (保持不變)
CREATE INDEX idx_workpiece_od_len ON workpiece_inventory (outer_diameter, length) 
WHERE status = 'available';

CREATE INDEX idx_workpiece_parent_id ON workpiece_inventory (parent_id);