--  庫存表 (使用 IDENTITY 代替 SERIAL，這是符合 SQL 標準的現代寫法)
-- CREATE TABLE workpiece_inventory (
--     id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
--     outer_diameter DECIMAL(10, 2) NOT NULL,
--     length DECIMAL(10, 2) NOT NULL,
    
--     -- 自關聯：指向母材的整數 ID
--     parent_id INTEGER REFERENCES workpiece_inventory(id) ON DELETE SET NULL,
    
--     -- 狀態：available (在庫), consumed (已切完), scrap (報廢/長度太短)
--     status VARCHAR(20) DEFAULT 'available', -- available, consumed, scrap
--     note TEXT,
--     created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
--     updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
-- );


--  建立需求表 (存放訂單或生產任務)
CREATE TABLE cutting_requirements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,  
    outer_diameter DECIMAL(10, 2) NOT NULL,
    length DECIMAL(10, 2) NOT NULL,
    quantity INTEGER DEFAULT 1,    
    
    -- 紀錄狀態：pending (待切割), completed (已完成)
    order_status VARCHAR(20) DEFAULT 'pending',
    
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);